### ISSUE TITLE
Demo is broken.

### ISSUE THREAD

**Issue by nelsonam** [alexcarpenter/library-jekyll-theme#3]
Hi Alex,

This looks very similar to what I want for my site, but your demo link is broken with a "Page Not Found".

http://alexcarpenter.me/library-jekyll-theme

**Comment by alexcarpenter** [comment]
@nelsonam it should be at http://alexcarpenter.github.io/library-jekyll-theme

**Comment by isaacwinter** [comment]
I'm still getting a 404 on that page.

<img width="1118" alt="screen shot 2017-03-26 at 9 21 47 am" src="https://cloud.githubusercontent.com/assets/26676310/24333014/ade515e8-1205-11e7-97a7-137eef39e4f5.png">

**Comment by alexcarpenter** [comment]
@isaacwinter just previewed the demo at http://alexcarpenter.github.io/library-jekyll-theme and is working correctly for me.
